# Generated by Django 5.0.6 on 2024-07-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
