# Generated by Django 5.0.6 on 2024-07-07 12:59

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_alter_imagemodel_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemodel",
            name="time",
        ),
        migrations.AddField(
            model_name="imagemodel",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 7, 7, 12, 59, 43, 943483, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
