# Generated by Django 5.0.6 on 2024-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_remove_imagemodel_time_imagemodel_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
