# Generated by Django 5.0.6 on 2024-10-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_imagemodel_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="JSONData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
    ]
