# Generated by Django 5.0.6 on 2024-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_jsondata"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ply_file", models.FileField(upload_to="ply_files/")),
            ],
        ),
    ]
