# Generated by Django 5.0.6 on 2024-11-13 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_plydata"),
    ]

    operations = [
        migrations.AddField(
            model_name="plydata",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
