# Generated by Django 5.0.6 on 2024-11-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_plydata_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="plydata",
            name="ply_file_url",
            field=models.URLField(blank=True),
        ),
    ]
